changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    - title: Breaking Changes 🛠
      types:
        - feat!
    - title: Features 🎉
      types:
        - feat
    - title: Bug Fixes 🐞
      types:
        - fix
    - title: Maintenance 🛠️
      types:
        - chore
        - docs
        - style
        - refactor
        - test