name: Bump Version and Create Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Bump version and generate changelog
      id: version
      uses: TriPSs/conventional-changelog-action@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        git-message: 'chore(release): {version}'
      
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.version.outputs.version_tag }}
        release_name: ${{ steps.version.outputs.release_title }}
        body: ${{ steps.version.outputs.changelog }}
        draft: false
        prerelease: false
