name: "Lint PR"

on:
  pull_request:
    branches:
      - main
      - develop
    types:
      - opened
      - reopened
      - edited
      - synchronize
  push:
    branches:
      - main
    types:
      - push
      - created
      - deleted
      - edited
      - renamed
      - reopened
jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}